service: github-info-api
variablesResolutionMode: 20210326

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
  
provider:
  name: aws
  region: ap-south-1
  runtime: nodejs14.x
  memorySize: 512
  lambdaHashingVersion: 20201221 # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  
  environment:
    GITHUB_ACCESS_TOKEN: 'Bearer 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'
  iam:
    role: 
      statements:      
        - Effect: Allow
          Action: 
            - cloudfront:updateDistribution
          Resource: "*"

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
      - http:
          path: '/{proxy+}'
          method: ANY
          cors:
            origin: '*'

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline